### ISSUE TITLE
Initial Release Loose-Ends Tracker

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/jako#2]
- [x] remove the logging messages with`Updating to db...` and `Starting database upload`
- [x] Change the name from `DistributeScan` to `DistributedScan`
- [x] Remove the failing tests for now
- [x] Replace `tmp/` with default linux temp directory `/tmp`
- [x] Add message that says "Started experiment in machine id : [machine_id]"
- [x] Add message that says "Completed experiment in machine id : [machine_id]"
- [x] ~~Add `DistributedScan` argument to decide of `local` is to be used as a machine in the experiment or not~~
- [x] `timestamp` has to be in human readable format `20:06/10-04-2022`
- [x] `timestamp` is missing
- [x] `experiment_id` `0-10-0, 0-10-1, 0-10-2...` where first digit is "stage", second is `machine_id` and third is `row`
- [x] table_name must follow `experiment_name` i.e. writes are made to the table which is same as `experiment_name`
- [x] If `experiment_name` is same but new params are added add the new column and populate previous as null
- [x] if `experiment_name` is same but params are removed, stop running with message "You have to change the experiment_name or add at least value for [missing param name/s] into the input parameters"
- [x] `Scan()` object and `DistributeScan` object are identical in terms of their namespace
- [x] fix all the style issues from [here](https://github.com/autonomio/talos/pull/579#issuecomment-1094325217)
- [x] Test with:
  - [x] Local + 1 x remote
  - [x] Local + 2 x remote
  - [x] 2 x remote 
- [ ] Update the docs (NOTE: a person without any prior knowledge should be able to follow the example in there and run everything successfully)
